//! Golden deserialize tests for all 62 event variants.

use auroran_sdk_rust::{parse_event, EventDomain};

#[test]
fn all_62_event_variants_deserialize_as_event_kind() {
    assert_eq!(62, 62);
    let ev = parse_event(&serde_json::json!({"seq": 1, "block_height": 100, "envelope_idx": 0, "kind": {"Core": {"BalanceChanged": {"owner": "0x1111222233334444555566667777888899990000", "delta": "1.0", "new_balance": "101.0", "reason": "Deposit"}}}})).expect("Core::BalanceChanged");
    assert_eq!(ev.path(), Some(("Core", "BalanceChanged")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Core));
    let kind = ev.kind().expect("typed kind Core::BalanceChanged");
    assert_eq!(kind.domain(), EventDomain::Core);
    assert_eq!(kind.variant(), "BalanceChanged");
    let ev = parse_event(&serde_json::json!({"seq": 2, "block_height": 101, "envelope_idx": 0, "kind": {"Core": {"MarkUpdated": {"market_id": 1, "mark_price": "1.0", "previous_mark_price": "0.9"}}}})).expect("Core::MarkUpdated");
    assert_eq!(ev.path(), Some(("Core", "MarkUpdated")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Core));
    let kind = ev.kind().expect("typed kind Core::MarkUpdated");
    assert_eq!(kind.domain(), EventDomain::Core);
    assert_eq!(kind.variant(), "MarkUpdated");
    let ev = parse_event(&serde_json::json!({"seq": 3, "block_height": 102, "envelope_idx": 0, "kind": {"Core": {"MarketStatsSnapshot": {"market_id": 1, "long_size": "1.0", "short_size": "0.5", "net_size": "0.5", "oracle_counter_pnl": "0.0", "fills_in_block": 2}}}})).expect("Core::MarketStatsSnapshot");
    assert_eq!(ev.path(), Some(("Core", "MarketStatsSnapshot")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Core));
    let kind = ev.kind().expect("typed kind Core::MarketStatsSnapshot");
    assert_eq!(kind.domain(), EventDomain::Core);
    assert_eq!(kind.variant(), "MarketStatsSnapshot");
    let ev = parse_event(&serde_json::json!({"seq": 4, "block_height": 103, "envelope_idx": 0, "kind": {"Core": {"Rejected": {"action_kind": "PlaceOrder", "reason": {"InsufficientBalance": {"required": "10.0", "have": "1.0"}}}}}})).expect("Core::Rejected");
    assert_eq!(ev.path(), Some(("Core", "Rejected")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Core));
    let kind = ev.kind().expect("typed kind Core::Rejected");
    assert_eq!(kind.domain(), EventDomain::Core);
    assert_eq!(kind.variant(), "Rejected");
    let ev = parse_event(&serde_json::json!({"seq": 5, "block_height": 104, "envelope_idx": 0, "kind": {"Core": {"BatchItemRejected": {"index": 0, "action_kind": "PlaceOrder", "reason": {"PostOnlyRejected": {}}}}}})).expect("Core::BatchItemRejected");
    assert_eq!(ev.path(), Some(("Core", "BatchItemRejected")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Core));
    let kind = ev.kind().expect("typed kind Core::BatchItemRejected");
    assert_eq!(kind.domain(), EventDomain::Core);
    assert_eq!(kind.variant(), "BatchItemRejected");
    let ev = parse_event(&serde_json::json!({"seq": 6, "block_height": 105, "envelope_idx": 0, "kind": {"Core": {"RuntimeReject": {"order_id": 1, "engine_reason": "PostOnlyWouldCross"}}}})).expect("Core::RuntimeReject");
    assert_eq!(ev.path(), Some(("Core", "RuntimeReject")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Core));
    let kind = ev.kind().expect("typed kind Core::RuntimeReject");
    assert_eq!(kind.domain(), EventDomain::Core);
    assert_eq!(kind.variant(), "RuntimeReject");
    let ev = parse_event(&serde_json::json!({"seq": 7, "block_height": 106, "envelope_idx": 0, "kind": {"Core": {"Bankruptcy": {"target_owner": "0x1111222233334444555566667777888899990000", "market_id": 1, "shortfall_amount": "10.0", "source": "Liquidation"}}}})).expect("Core::Bankruptcy");
    assert_eq!(ev.path(), Some(("Core", "Bankruptcy")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Core));
    let kind = ev.kind().expect("typed kind Core::Bankruptcy");
    assert_eq!(kind.domain(), EventDomain::Core);
    assert_eq!(kind.variant(), "Bankruptcy");
    let ev = parse_event(&serde_json::json!({"seq": 8, "block_height": 107, "envelope_idx": 0, "kind": {"Core": {"UserFeeRateChanged": {"owner": "0x1111222233334444555566667777888899990000", "maker_fee_rate": "0.0001", "taker_fee_rate": "0.0005"}}}})).expect("Core::UserFeeRateChanged");
    assert_eq!(ev.path(), Some(("Core", "UserFeeRateChanged")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Core));
    let kind = ev.kind().expect("typed kind Core::UserFeeRateChanged");
    assert_eq!(kind.domain(), EventDomain::Core);
    assert_eq!(kind.variant(), "UserFeeRateChanged");
    let ev = parse_event(&serde_json::json!({"seq": 9, "block_height": 108, "envelope_idx": 0, "kind": {"Core": {"ReferrerRegistered": {"owner": "0x1111222233334444555566667777888899990000", "code": "ABC"}}}})).expect("Core::ReferrerRegistered");
    assert_eq!(ev.path(), Some(("Core", "ReferrerRegistered")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Core));
    let kind = ev.kind().expect("typed kind Core::ReferrerRegistered");
    assert_eq!(kind.domain(), EventDomain::Core);
    assert_eq!(kind.variant(), "ReferrerRegistered");
    let ev = parse_event(&serde_json::json!({"seq": 10, "block_height": 109, "envelope_idx": 0, "kind": {"Core": {"ReferrerBound": {"owner": "0x1111222233334444555566667777888899990000", "code": "ABC"}}}})).expect("Core::ReferrerBound");
    assert_eq!(ev.path(), Some(("Core", "ReferrerBound")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Core));
    let kind = ev.kind().expect("typed kind Core::ReferrerBound");
    assert_eq!(kind.domain(), EventDomain::Core);
    assert_eq!(kind.variant(), "ReferrerBound");
    let ev = parse_event(&serde_json::json!({"seq": 11, "block_height": 110, "envelope_idx": 0, "kind": {"Core": {"InviterKeepRatioChanged": {"owner": "0x1111222233334444555566667777888899990000", "old_ratio_bps": 5000, "new_ratio_bps": 6000}}}})).expect("Core::InviterKeepRatioChanged");
    assert_eq!(ev.path(), Some(("Core", "InviterKeepRatioChanged")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Core));
    let kind = ev.kind().expect("typed kind Core::InviterKeepRatioChanged");
    assert_eq!(kind.domain(), EventDomain::Core);
    assert_eq!(kind.variant(), "InviterKeepRatioChanged");
    let ev = parse_event(&serde_json::json!({"seq": 12, "block_height": 111, "envelope_idx": 0, "kind": {"Core": {"RebatePaid": {"trader": "0x1111222233334444555566667777888899990000", "inviter": "0x2222333344445555666677778888999900001111", "referral_code": "ABC", "total_amount": "1.0", "inviter_share": "0.5", "invitee_share": "0.5"}}}})).expect("Core::RebatePaid");
    assert_eq!(ev.path(), Some(("Core", "RebatePaid")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Core));
    let kind = ev.kind().expect("typed kind Core::RebatePaid");
    assert_eq!(kind.domain(), EventDomain::Core);
    assert_eq!(kind.variant(), "RebatePaid");
    let ev = parse_event(&serde_json::json!({"seq": 13, "block_height": 112, "envelope_idx": 0, "kind": {"Core": {"DeadMansSwitchScheduled": {"owner": "0x1111222233334444555566667777888899990000", "trigger_time_ms": 1234567890}}}})).expect("Core::DeadMansSwitchScheduled");
    assert_eq!(ev.path(), Some(("Core", "DeadMansSwitchScheduled")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Core));
    let kind = ev.kind().expect("typed kind Core::DeadMansSwitchScheduled");
    assert_eq!(kind.domain(), EventDomain::Core);
    assert_eq!(kind.variant(), "DeadMansSwitchScheduled");
    let ev = parse_event(&serde_json::json!({"seq": 14, "block_height": 113, "envelope_idx": 0, "kind": {"Core": {"DeadMansSwitchTriggered": {"owner": "0x1111222233334444555566667777888899990000", "cancelled": 3}}}})).expect("Core::DeadMansSwitchTriggered");
    assert_eq!(ev.path(), Some(("Core", "DeadMansSwitchTriggered")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Core));
    let kind = ev.kind().expect("typed kind Core::DeadMansSwitchTriggered");
    assert_eq!(kind.domain(), EventDomain::Core);
    assert_eq!(kind.variant(), "DeadMansSwitchTriggered");
    let ev = parse_event(&serde_json::json!({"seq": 15, "block_height": 114, "envelope_idx": 0, "kind": {"Exec": {"OrderAccepted": {"order_id": 1, "owner": "0x1111222233334444555566667777888899990000", "market_id": 1, "side": "Bid", "limit_price": "1.0", "qty": "0.1", "tif": "Gtc"}}}})).expect("Exec::OrderAccepted");
    assert_eq!(ev.path(), Some(("Exec", "OrderAccepted")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Exec));
    let kind = ev.kind().expect("typed kind Exec::OrderAccepted");
    assert_eq!(kind.domain(), EventDomain::Exec);
    assert_eq!(kind.variant(), "OrderAccepted");
    let ev = parse_event(&serde_json::json!({"seq": 16, "block_height": 115, "envelope_idx": 0, "kind": {"Exec": {"Filled": {"taker_order_id": 1, "maker_order_id": 2, "market_id": 1, "taker_owner": "0x1111222233334444555566667777888899990000", "maker_owner": "0x2222333344445555666677778888999900001111", "price": "100.0", "qty": "0.00100", "notional": "0.100000", "taker_fee": "0.000050", "maker_fee": "-0.000010", "aggressor_side": "Bid"}}}})).expect("Exec::Filled");
    assert_eq!(ev.path(), Some(("Exec", "Filled")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Exec));
    let kind = ev.kind().expect("typed kind Exec::Filled");
    assert_eq!(kind.domain(), EventDomain::Exec);
    assert_eq!(kind.variant(), "Filled");
    let ev = parse_event(&serde_json::json!({"seq": 17, "block_height": 116, "envelope_idx": 0, "kind": {"Exec": {"OrderResting": {"order_id": 1, "owner": "0x1111222233334444555566667777888899990000", "market_id": 1, "resting": {"price": "1.0", "qty": "0.1", "remaining": "0.1", "im_reserved": "0.5", "prepaid_maker_fee": "0.0"}}}}})).expect("Exec::OrderResting");
    assert_eq!(ev.path(), Some(("Exec", "OrderResting")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Exec));
    let kind = ev.kind().expect("typed kind Exec::OrderResting");
    assert_eq!(kind.domain(), EventDomain::Exec);
    assert_eq!(kind.variant(), "OrderResting");
    let ev = parse_event(&serde_json::json!({"seq": 18, "block_height": 117, "envelope_idx": 0, "kind": {"Exec": {"OrderDone": {"order_id": 1, "owner": "0x1111222233334444555566667777888899990000", "market_id": 1, "reason": "Filled", "remaining": "0.0"}}}})).expect("Exec::OrderDone");
    assert_eq!(ev.path(), Some(("Exec", "OrderDone")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Exec));
    let kind = ev.kind().expect("typed kind Exec::OrderDone");
    assert_eq!(kind.domain(), EventDomain::Exec);
    assert_eq!(kind.variant(), "OrderDone");
    let ev = parse_event(&serde_json::json!({"seq": 19, "block_height": 118, "envelope_idx": 0, "kind": {"Exec": {"PositionUpdated": {"owner": "0x1111222233334444555566667777888899990000", "market_id": 1, "old_size": "0.0", "new_size": "0.1", "new_entry_vwap": "100.0", "realized_pnl": "0.0"}}}})).expect("Exec::PositionUpdated");
    assert_eq!(ev.path(), Some(("Exec", "PositionUpdated")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Exec));
    let kind = ev.kind().expect("typed kind Exec::PositionUpdated");
    assert_eq!(kind.domain(), EventDomain::Exec);
    assert_eq!(kind.variant(), "PositionUpdated");
    let ev = parse_event(&serde_json::json!({"seq": 20, "block_height": 119, "envelope_idx": 0, "kind": {"Exec": {"PositionFlattened": {"owner": "0x1111222233334444555566667777888899990000", "market_id": 1, "old_size": "0.5"}}}})).expect("Exec::PositionFlattened");
    assert_eq!(ev.path(), Some(("Exec", "PositionFlattened")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Exec));
    let kind = ev.kind().expect("typed kind Exec::PositionFlattened");
    assert_eq!(kind.domain(), EventDomain::Exec);
    assert_eq!(kind.variant(), "PositionFlattened");
    let ev = parse_event(&serde_json::json!({"seq": 21, "block_height": 120, "envelope_idx": 0, "kind": {"Exec": {"OrderCancelledByPositionFlat": {"order_id": 1, "owner": "0x1111222233334444555566667777888899990000", "market_id": 1, "remaining": "0.1"}}}})).expect("Exec::OrderCancelledByPositionFlat");
    assert_eq!(ev.path(), Some(("Exec", "OrderCancelledByPositionFlat")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Exec));
    let kind = ev.kind().expect("typed kind Exec::OrderCancelledByPositionFlat");
    assert_eq!(kind.domain(), EventDomain::Exec);
    assert_eq!(kind.variant(), "OrderCancelledByPositionFlat");
    let ev = parse_event(&serde_json::json!({"seq": 22, "block_height": 121, "envelope_idx": 0, "kind": {"Exec": {"TriggerCancelledByPositionFlat": {"trigger_id": 7, "owner": "0x1111222233334444555566667777888899990000", "market_id": 1}}}})).expect("Exec::TriggerCancelledByPositionFlat");
    assert_eq!(ev.path(), Some(("Exec", "TriggerCancelledByPositionFlat")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Exec));
    let kind = ev.kind().expect("typed kind Exec::TriggerCancelledByPositionFlat");
    assert_eq!(kind.domain(), EventDomain::Exec);
    assert_eq!(kind.variant(), "TriggerCancelledByPositionFlat");
    let ev = parse_event(&serde_json::json!({"seq": 23, "block_height": 122, "envelope_idx": 0, "kind": {"Exec": {"IsolatedMarginUpdated": {"owner": "0x1111222233334444555566667777888899990000", "market_id": 1, "new_isolated_margin": "10.0"}}}})).expect("Exec::IsolatedMarginUpdated");
    assert_eq!(ev.path(), Some(("Exec", "IsolatedMarginUpdated")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Exec));
    let kind = ev.kind().expect("typed kind Exec::IsolatedMarginUpdated");
    assert_eq!(kind.domain(), EventDomain::Exec);
    assert_eq!(kind.variant(), "IsolatedMarginUpdated");
    let ev = parse_event(&serde_json::json!({"seq": 24, "block_height": 123, "envelope_idx": 0, "kind": {"Exec": {"LeverageUpdated": {"owner": "0x1111222233334444555566667777888899990000", "market_id": 1, "leverage": 25}}}})).expect("Exec::LeverageUpdated");
    assert_eq!(ev.path(), Some(("Exec", "LeverageUpdated")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Exec));
    let kind = ev.kind().expect("typed kind Exec::LeverageUpdated");
    assert_eq!(kind.domain(), EventDomain::Exec);
    assert_eq!(kind.variant(), "LeverageUpdated");
    let ev = parse_event(&serde_json::json!({"seq": 25, "block_height": 124, "envelope_idx": 0, "kind": {"Exec": {"MarginModeUpdated": {"owner": "0x1111222233334444555566667777888899990000", "market_id": 1, "margin_mode": "Cross"}}}})).expect("Exec::MarginModeUpdated");
    assert_eq!(ev.path(), Some(("Exec", "MarginModeUpdated")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Exec));
    let kind = ev.kind().expect("typed kind Exec::MarginModeUpdated");
    assert_eq!(kind.domain(), EventDomain::Exec);
    assert_eq!(kind.variant(), "MarginModeUpdated");
    let ev = parse_event(&serde_json::json!({"seq": 26, "block_height": 125, "envelope_idx": 0, "kind": {"Exec": {"PositionForceClosedAtMark": {"target": "0x1111222233334444555566667777888899990000", "market_id": 1, "size": "0.1", "mark_price": "100.0", "realized_pnl": "-1.0"}}}})).expect("Exec::PositionForceClosedAtMark");
    assert_eq!(ev.path(), Some(("Exec", "PositionForceClosedAtMark")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Exec));
    let kind = ev.kind().expect("typed kind Exec::PositionForceClosedAtMark");
    assert_eq!(kind.domain(), EventDomain::Exec);
    assert_eq!(kind.variant(), "PositionForceClosedAtMark");
    let ev = parse_event(&serde_json::json!({"seq": 27, "block_height": 126, "envelope_idx": 0, "kind": {"Exec": {"OracleQuoteAccepted": {"market_id": 1, "quoter": "0x1111222233334444555566667777888899990000", "bid_price": "99.0", "ask_price": "101.0", "mark_price": "100.0", "last_price": "100.0", "volume": "1.0", "source_ts_ms": 1, "sequence_id": 1}}}})).expect("Exec::OracleQuoteAccepted");
    assert_eq!(ev.path(), Some(("Exec", "OracleQuoteAccepted")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Exec));
    let kind = ev.kind().expect("typed kind Exec::OracleQuoteAccepted");
    assert_eq!(kind.domain(), EventDomain::Exec);
    assert_eq!(kind.variant(), "OracleQuoteAccepted");
    let ev = parse_event(&serde_json::json!({"seq": 28, "block_height": 127, "envelope_idx": 0, "kind": {"Exec": {"OracleQuoteRejected": {"market_id": 1, "quoter": "0x1111222233334444555566667777888899990000", "reason": "QuoteBidAskInvalid"}}}})).expect("Exec::OracleQuoteRejected");
    assert_eq!(ev.path(), Some(("Exec", "OracleQuoteRejected")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Exec));
    let kind = ev.kind().expect("typed kind Exec::OracleQuoteRejected");
    assert_eq!(kind.domain(), EventDomain::Exec);
    assert_eq!(kind.variant(), "OracleQuoteRejected");
    let ev = parse_event(&serde_json::json!({"seq": 29, "block_height": 128, "envelope_idx": 0, "kind": {"Exec": {"OracleCounterDepleted": {"market_id": 1, "required": "10.0", "available": "1.0"}}}})).expect("Exec::OracleCounterDepleted");
    assert_eq!(ev.path(), Some(("Exec", "OracleCounterDepleted")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Exec));
    let kind = ev.kind().expect("typed kind Exec::OracleCounterDepleted");
    assert_eq!(kind.domain(), EventDomain::Exec);
    assert_eq!(kind.variant(), "OracleCounterDepleted");
    let ev = parse_event(&serde_json::json!({"seq": 30, "block_height": 129, "envelope_idx": 0, "kind": {"Exec": {"MarketHaltedQuoteStale": {"market_id": 1, "last_quote_ts_ms": 1, "block_ts_ms": 2}}}})).expect("Exec::MarketHaltedQuoteStale");
    assert_eq!(ev.path(), Some(("Exec", "MarketHaltedQuoteStale")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Exec));
    let kind = ev.kind().expect("typed kind Exec::MarketHaltedQuoteStale");
    assert_eq!(kind.domain(), EventDomain::Exec);
    assert_eq!(kind.variant(), "MarketHaltedQuoteStale");
    let ev = parse_event(&serde_json::json!({"seq": 31, "block_height": 130, "envelope_idx": 0, "kind": {"Exec": {"MarketResumedAfterQuote": {"market_id": 1}}}})).expect("Exec::MarketResumedAfterQuote");
    assert_eq!(ev.path(), Some(("Exec", "MarketResumedAfterQuote")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Exec));
    let kind = ev.kind().expect("typed kind Exec::MarketResumedAfterQuote");
    assert_eq!(kind.domain(), EventDomain::Exec);
    assert_eq!(kind.variant(), "MarketResumedAfterQuote");
    let ev = parse_event(&serde_json::json!({"seq": 32, "block_height": 131, "envelope_idx": 0, "kind": {"Exec": {"QuoteRejectStorm": {"market_id": 1, "quoter": "0x1111222233334444555566667777888899990000", "streak": 5}}}})).expect("Exec::QuoteRejectStorm");
    assert_eq!(ev.path(), Some(("Exec", "QuoteRejectStorm")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Exec));
    let kind = ev.kind().expect("typed kind Exec::QuoteRejectStorm");
    assert_eq!(kind.domain(), EventDomain::Exec);
    assert_eq!(kind.variant(), "QuoteRejectStorm");
    let ev = parse_event(&serde_json::json!({"seq": 33, "block_height": 132, "envelope_idx": 0, "kind": {"Oco": {"OrderCancelledByOcoSibling": {"order_id": 1, "owner": "0x1111222233334444555566667777888899990000", "market_id": 1, "remaining": "0.1", "pair_id": 1, "winning_leg": {"Order": 42}}}}})).expect("Oco::OrderCancelledByOcoSibling");
    assert_eq!(ev.path(), Some(("Oco", "OrderCancelledByOcoSibling")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Oco));
    let kind = ev.kind().expect("typed kind Oco::OrderCancelledByOcoSibling");
    assert_eq!(kind.domain(), EventDomain::Oco);
    assert_eq!(kind.variant(), "OrderCancelledByOcoSibling");
    let ev = parse_event(&serde_json::json!({"seq": 34, "block_height": 133, "envelope_idx": 0, "kind": {"Oco": {"TriggerOrderCancelled": {"trigger_id": 7, "market_id": 1, "owner": "0x1111222233334444555566667777888899990000", "reason": "OcoSibling"}}}})).expect("Oco::TriggerOrderCancelled");
    assert_eq!(ev.path(), Some(("Oco", "TriggerOrderCancelled")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Oco));
    let kind = ev.kind().expect("typed kind Oco::TriggerOrderCancelled");
    assert_eq!(kind.domain(), EventDomain::Oco);
    assert_eq!(kind.variant(), "TriggerOrderCancelled");
    let ev = parse_event(&serde_json::json!({"seq": 35, "block_height": 134, "envelope_idx": 0, "kind": {"Oco": {"LimitTriggerOrderCancelled": {"trigger_id": 8, "market_id": 1, "owner": "0x1111222233334444555566667777888899990000", "reason": "OcoSibling"}}}})).expect("Oco::LimitTriggerOrderCancelled");
    assert_eq!(ev.path(), Some(("Oco", "LimitTriggerOrderCancelled")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Oco));
    let kind = ev.kind().expect("typed kind Oco::LimitTriggerOrderCancelled");
    assert_eq!(kind.domain(), EventDomain::Oco);
    assert_eq!(kind.variant(), "LimitTriggerOrderCancelled");
    let ev = parse_event(&serde_json::json!({"seq": 36, "block_height": 135, "envelope_idx": 0, "kind": {"Oco": {"OcoPairResolved": {"pair_id": 1, "owner": "0x1111222233334444555566667777888899990000", "market_id": 1, "winner_leg": {"Order": 42}, "reason": "OrderResolved"}}}})).expect("Oco::OcoPairResolved");
    assert_eq!(ev.path(), Some(("Oco", "OcoPairResolved")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Oco));
    let kind = ev.kind().expect("typed kind Oco::OcoPairResolved");
    assert_eq!(kind.domain(), EventDomain::Oco);
    assert_eq!(kind.variant(), "OcoPairResolved");
    let ev = parse_event(&serde_json::json!({"seq": 37, "block_height": 136, "envelope_idx": 0, "kind": {"Liquidation": {"Liquidated": {"target": "0x1111222233334444555566667777888899990000", "market_id": 1, "closed_via_book": "0.1", "force_closed_at_mark": "0.0", "total_realized_pnl": "-1.0", "mark_price": "100.0"}}}})).expect("Liquidation::Liquidated");
    assert_eq!(ev.path(), Some(("Liquidation", "Liquidated")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Liquidation));
    let kind = ev.kind().expect("typed kind Liquidation::Liquidated");
    assert_eq!(kind.domain(), EventDomain::Liquidation);
    assert_eq!(kind.variant(), "Liquidated");
    let ev = parse_event(&serde_json::json!({"seq": 38, "block_height": 137, "envelope_idx": 0, "kind": {"Trigger": {"TriggerOrderPlaced": {"trigger_id": 7, "market_id": 1, "owner": "0x1111222233334444555566667777888899990000", "trigger_price": "100.0", "trigger_direction": "Above", "payload": {"Market": {"side": "Bid", "qty": "0.1", "reduce_only": false}}, "expires_at_ms": null}}}})).expect("Trigger::TriggerOrderPlaced");
    assert_eq!(ev.path(), Some(("Trigger", "TriggerOrderPlaced")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Trigger));
    let kind = ev.kind().expect("typed kind Trigger::TriggerOrderPlaced");
    assert_eq!(kind.domain(), EventDomain::Trigger);
    assert_eq!(kind.variant(), "TriggerOrderPlaced");
    let ev = parse_event(&serde_json::json!({"seq": 39, "block_height": 138, "envelope_idx": 0, "kind": {"Trigger": {"TriggerOrderAmended": {"trigger_id": 7, "market_id": 1, "owner": "0x1111222233334444555566667777888899990000", "trigger_price": "101.0", "trigger_direction": "Above", "payload": {"Market": {"side": "Bid", "qty": "0.1", "reduce_only": false}}, "expires_at_ms": null}}}})).expect("Trigger::TriggerOrderAmended");
    assert_eq!(ev.path(), Some(("Trigger", "TriggerOrderAmended")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Trigger));
    let kind = ev.kind().expect("typed kind Trigger::TriggerOrderAmended");
    assert_eq!(kind.domain(), EventDomain::Trigger);
    assert_eq!(kind.variant(), "TriggerOrderAmended");
    let ev = parse_event(&serde_json::json!({"seq": 40, "block_height": 139, "envelope_idx": 0, "kind": {"Trigger": {"TriggerOrderCancelled": {"trigger_id": 7, "market_id": 1, "owner": "0x1111222233334444555566667777888899990000", "reason": "ByOwner"}}}})).expect("Trigger::TriggerOrderCancelled");
    assert_eq!(ev.path(), Some(("Trigger", "TriggerOrderCancelled")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Trigger));
    let kind = ev.kind().expect("typed kind Trigger::TriggerOrderCancelled");
    assert_eq!(kind.domain(), EventDomain::Trigger);
    assert_eq!(kind.variant(), "TriggerOrderCancelled");
    let ev = parse_event(&serde_json::json!({"seq": 41, "block_height": 140, "envelope_idx": 0, "kind": {"Trigger": {"LimitTriggerOrderCancelled": {"trigger_id": 8, "market_id": 1, "owner": "0x1111222233334444555566667777888899990000", "reason": "ByOwner"}}}})).expect("Trigger::LimitTriggerOrderCancelled");
    assert_eq!(ev.path(), Some(("Trigger", "LimitTriggerOrderCancelled")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Trigger));
    let kind = ev.kind().expect("typed kind Trigger::LimitTriggerOrderCancelled");
    assert_eq!(kind.domain(), EventDomain::Trigger);
    assert_eq!(kind.variant(), "LimitTriggerOrderCancelled");
    let ev = parse_event(&serde_json::json!({"seq": 42, "block_height": 141, "envelope_idx": 0, "kind": {"Trigger": {"TriggerOrderExpired": {"trigger_id": 7, "market_id": 1, "owner": "0x1111222233334444555566667777888899990000"}}}})).expect("Trigger::TriggerOrderExpired");
    assert_eq!(ev.path(), Some(("Trigger", "TriggerOrderExpired")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Trigger));
    let kind = ev.kind().expect("typed kind Trigger::TriggerOrderExpired");
    assert_eq!(kind.domain(), EventDomain::Trigger);
    assert_eq!(kind.variant(), "TriggerOrderExpired");
    let ev = parse_event(&serde_json::json!({"seq": 43, "block_height": 142, "envelope_idx": 0, "kind": {"Trigger": {"TriggerActivated": {"trigger_id": 7, "market_id": 1, "owner": "0x1111222233334444555566667777888899990000", "mark_price": "100.0", "trigger_price": "99.0"}}}})).expect("Trigger::TriggerActivated");
    assert_eq!(ev.path(), Some(("Trigger", "TriggerActivated")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Trigger));
    let kind = ev.kind().expect("typed kind Trigger::TriggerActivated");
    assert_eq!(kind.domain(), EventDomain::Trigger);
    assert_eq!(kind.variant(), "TriggerActivated");
    let ev = parse_event(&serde_json::json!({"seq": 44, "block_height": 143, "envelope_idx": 0, "kind": {"Trigger": {"TriggerFireFailed": {"trigger_id": 7, "market_id": 1, "owner": "0x1111222233334444555566667777888899990000", "reason": {"InsufficientBalance": {"required": "1.0", "have": "0.0"}}}}}})).expect("Trigger::TriggerFireFailed");
    assert_eq!(ev.path(), Some(("Trigger", "TriggerFireFailed")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Trigger));
    let kind = ev.kind().expect("typed kind Trigger::TriggerFireFailed");
    assert_eq!(kind.domain(), EventDomain::Trigger);
    assert_eq!(kind.variant(), "TriggerFireFailed");
    let ev = parse_event(&serde_json::json!({"seq": 45, "block_height": 144, "envelope_idx": 0, "kind": {"Trigger": {"OcoPairPlaced": {"pair_id": 1, "owner": "0x1111222233334444555566667777888899990000", "market_id": 1, "legs": {"TwoTriggers": {"primary_trigger_id": 7, "primary_kind": "StopMarket", "secondary_trigger_id": 8, "secondary_kind": "StopLimit"}}, "client_pair_id": null, "parent_order_id": null}}}})).expect("Trigger::OcoPairPlaced");
    assert_eq!(ev.path(), Some(("Trigger", "OcoPairPlaced")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Trigger));
    let kind = ev.kind().expect("typed kind Trigger::OcoPairPlaced");
    assert_eq!(kind.domain(), EventDomain::Trigger);
    assert_eq!(kind.variant(), "OcoPairPlaced");
    let ev = parse_event(&serde_json::json!({"seq": 46, "block_height": 145, "envelope_idx": 0, "kind": {"Trigger": {"OcoPairResolved": {"pair_id": 2, "owner": "0x1111222233334444555566667777888899990000", "market_id": 1, "winner_leg": null, "reason": "ManualCancel"}}}})).expect("Trigger::OcoPairResolved");
    assert_eq!(ev.path(), Some(("Trigger", "OcoPairResolved")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Trigger));
    let kind = ev.kind().expect("typed kind Trigger::OcoPairResolved");
    assert_eq!(kind.domain(), EventDomain::Trigger);
    assert_eq!(kind.variant(), "OcoPairResolved");
    let ev = parse_event(&serde_json::json!({"seq": 47, "block_height": 146, "envelope_idx": 0, "kind": {"Bridge": {"DepositRecorded": {"seq": 1, "external_ref": {"chain": "bsc", "seq": 1}, "tx_hash": "0xabc", "account": "0x1111222233334444555566667777888899990000", "amount": "10.0"}}}})).expect("Bridge::DepositRecorded");
    assert_eq!(ev.path(), Some(("Bridge", "DepositRecorded")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Bridge));
    let kind = ev.kind().expect("typed kind Bridge::DepositRecorded");
    assert_eq!(kind.domain(), EventDomain::Bridge);
    assert_eq!(kind.variant(), "DepositRecorded");
    let ev = parse_event(&serde_json::json!({"seq": 48, "block_height": 147, "envelope_idx": 0, "kind": {"Bridge": {"DepositCredited": {"seq": 1, "owner": "0x1111222233334444555566667777888899990000", "amount": "10.0", "new_balance": "110.0"}}}})).expect("Bridge::DepositCredited");
    assert_eq!(ev.path(), Some(("Bridge", "DepositCredited")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Bridge));
    let kind = ev.kind().expect("typed kind Bridge::DepositCredited");
    assert_eq!(kind.domain(), EventDomain::Bridge);
    assert_eq!(kind.variant(), "DepositCredited");
    let ev = parse_event(&serde_json::json!({"seq": 49, "block_height": 148, "envelope_idx": 0, "kind": {"Bridge": {"WithdrawRequested": {"request_id": 1, "owner": "0x1111222233334444555566667777888899990000", "amount": "10.0", "chain": "bsc", "new_balance": "90.0"}}}})).expect("Bridge::WithdrawRequested");
    assert_eq!(ev.path(), Some(("Bridge", "WithdrawRequested")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Bridge));
    let kind = ev.kind().expect("typed kind Bridge::WithdrawRequested");
    assert_eq!(kind.domain(), EventDomain::Bridge);
    assert_eq!(kind.variant(), "WithdrawRequested");
    let ev = parse_event(&serde_json::json!({"seq": 50, "block_height": 149, "envelope_idx": 0, "kind": {"Bridge": {"WithdrawSettled": {"request_id": 1, "owner": "0x1111222233334444555566667777888899990000", "amount": "10.0", "tx_hash": "0xdef"}}}})).expect("Bridge::WithdrawSettled");
    assert_eq!(ev.path(), Some(("Bridge", "WithdrawSettled")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Bridge));
    let kind = ev.kind().expect("typed kind Bridge::WithdrawSettled");
    assert_eq!(kind.domain(), EventDomain::Bridge);
    assert_eq!(kind.variant(), "WithdrawSettled");
    let ev = parse_event(&serde_json::json!({"seq": 51, "block_height": 150, "envelope_idx": 0, "kind": {"Bridge": {"WithdrawRefunded": {"request_id": 1, "owner": "0x1111222233334444555566667777888899990000", "amount": "10.0", "reason_code": 1, "new_balance": "100.0"}}}})).expect("Bridge::WithdrawRefunded");
    assert_eq!(ev.path(), Some(("Bridge", "WithdrawRefunded")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Bridge));
    let kind = ev.kind().expect("typed kind Bridge::WithdrawRefunded");
    assert_eq!(kind.domain(), EventDomain::Bridge);
    assert_eq!(kind.variant(), "WithdrawRefunded");
    let ev = parse_event(&serde_json::json!({"seq": 52, "block_height": 151, "envelope_idx": 0, "kind": {"Bridge": {"SettlementPausedChanged": {"paused": true}}}})).expect("Bridge::SettlementPausedChanged");
    assert_eq!(ev.path(), Some(("Bridge", "SettlementPausedChanged")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Bridge));
    let kind = ev.kind().expect("typed kind Bridge::SettlementPausedChanged");
    assert_eq!(kind.domain(), EventDomain::Bridge);
    assert_eq!(kind.variant(), "SettlementPausedChanged");
    let ev = parse_event(&serde_json::json!({"seq": 53, "block_height": 152, "envelope_idx": 0, "kind": {"Ops": {"AccountRoleChanged": {"target": "0x1111222233334444555566667777888899990000", "role": "Trader", "granted": true, "new_mask": 1}}}})).expect("Ops::AccountRoleChanged");
    assert_eq!(ev.path(), Some(("Ops", "AccountRoleChanged")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Ops));
    let kind = ev.kind().expect("typed kind Ops::AccountRoleChanged");
    assert_eq!(kind.domain(), EventDomain::Ops);
    assert_eq!(kind.variant(), "AccountRoleChanged");
    let ev = parse_event(&serde_json::json!({"seq": 54, "block_height": 153, "envelope_idx": 0, "kind": {"Ops": {"AgentRegistered": {"owner": "0x1111222233334444555566667777888899990000", "agent_address": "0x2222333344445555666677778888999900001111", "role_mask": 1, "expires_at_ms": 999}}}})).expect("Ops::AgentRegistered");
    assert_eq!(ev.path(), Some(("Ops", "AgentRegistered")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Ops));
    let kind = ev.kind().expect("typed kind Ops::AgentRegistered");
    assert_eq!(kind.domain(), EventDomain::Ops);
    assert_eq!(kind.variant(), "AgentRegistered");
    let ev = parse_event(&serde_json::json!({"seq": 55, "block_height": 154, "envelope_idx": 0, "kind": {"Ops": {"AgentRevoked": {"owner": "0x1111222233334444555566667777888899990000", "agent_address": "0x2222333344445555666677778888999900001111"}}}})).expect("Ops::AgentRevoked");
    assert_eq!(ev.path(), Some(("Ops", "AgentRevoked")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Ops));
    let kind = ev.kind().expect("typed kind Ops::AgentRevoked");
    assert_eq!(kind.domain(), EventDomain::Ops);
    assert_eq!(kind.variant(), "AgentRevoked");
    let ev = parse_event(&serde_json::json!({"seq": 56, "block_height": 155, "envelope_idx": 0, "kind": {"Ops": {"EmergencyHaltChanged": {"market_id": 1, "halted": true}}}})).expect("Ops::EmergencyHaltChanged");
    assert_eq!(ev.path(), Some(("Ops", "EmergencyHaltChanged")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Ops));
    let kind = ev.kind().expect("typed kind Ops::EmergencyHaltChanged");
    assert_eq!(kind.domain(), EventDomain::Ops);
    assert_eq!(kind.variant(), "EmergencyHaltChanged");
    let ev = parse_event(&serde_json::json!({"seq": 57, "block_height": 156, "envelope_idx": 0, "kind": {"Ops": {"MarketCreated": {"market_id": 1, "kind": "Native", "lifecycle": "Active"}}}})).expect("Ops::MarketCreated");
    assert_eq!(ev.path(), Some(("Ops", "MarketCreated")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Ops));
    let kind = ev.kind().expect("typed kind Ops::MarketCreated");
    assert_eq!(kind.domain(), EventDomain::Ops);
    assert_eq!(kind.variant(), "MarketCreated");
    let ev = parse_event(&serde_json::json!({"seq": 58, "block_height": 157, "envelope_idx": 0, "kind": {"Ops": {"MarketLifecycleChanged": {"market_id": 1, "from": "Active", "to": "Halted"}}}})).expect("Ops::MarketLifecycleChanged");
    assert_eq!(ev.path(), Some(("Ops", "MarketLifecycleChanged")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Ops));
    let kind = ev.kind().expect("typed kind Ops::MarketLifecycleChanged");
    assert_eq!(kind.domain(), EventDomain::Ops);
    assert_eq!(kind.variant(), "MarketLifecycleChanged");
    let ev = parse_event(&serde_json::json!({"seq": 59, "block_height": 158, "envelope_idx": 0, "kind": {"Ops": {"FeeRecipientChanged": {"market_id": 1, "old_recipient": "0x1111222233334444555566667777888899990000", "new_recipient": "0x2222333344445555666677778888999900001111"}}}})).expect("Ops::FeeRecipientChanged");
    assert_eq!(ev.path(), Some(("Ops", "FeeRecipientChanged")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Ops));
    let kind = ev.kind().expect("typed kind Ops::FeeRecipientChanged");
    assert_eq!(kind.domain(), EventDomain::Ops);
    assert_eq!(kind.variant(), "FeeRecipientChanged");
    let ev = parse_event(&serde_json::json!({"seq": 60, "block_height": 159, "envelope_idx": 0, "kind": {"Ops": {"MarketConfigAmended": {"market_id": 1, "max_leverage": 50}}}})).expect("Ops::MarketConfigAmended");
    assert_eq!(ev.path(), Some(("Ops", "MarketConfigAmended")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Ops));
    let kind = ev.kind().expect("typed kind Ops::MarketConfigAmended");
    assert_eq!(kind.domain(), EventDomain::Ops);
    assert_eq!(kind.variant(), "MarketConfigAmended");
    let ev = parse_event(&serde_json::json!({"seq": 61, "block_height": 160, "envelope_idx": 0, "kind": {"Ops": {"GlobalRebateRatioChanged": {"old_ratio_bps": 1000, "new_ratio_bps": 2000}}}})).expect("Ops::GlobalRebateRatioChanged");
    assert_eq!(ev.path(), Some(("Ops", "GlobalRebateRatioChanged")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Ops));
    let kind = ev.kind().expect("typed kind Ops::GlobalRebateRatioChanged");
    assert_eq!(kind.domain(), EventDomain::Ops);
    assert_eq!(kind.variant(), "GlobalRebateRatioChanged");
    let ev = parse_event(&serde_json::json!({"seq": 62, "block_height": 161, "envelope_idx": 0, "kind": {"Ops": {"AccountRebateRatioChanged": {"owner": "0x1111222233334444555566667777888899990000", "ratio_bps": 3000}}}})).expect("Ops::AccountRebateRatioChanged");
    assert_eq!(ev.path(), Some(("Ops", "AccountRebateRatioChanged")));
    assert_eq!(ev.domain_enum(), Some(EventDomain::Ops));
    let kind = ev.kind().expect("typed kind Ops::AccountRebateRatioChanged");
    assert_eq!(kind.domain(), EventDomain::Ops);
    assert_eq!(kind.variant(), "AccountRebateRatioChanged");
}
