use crate::wire::Action;

pub(crate) fn action_method_name(action: &Action) -> &'static str {
    match action {
        Action::PlaceOrder(_) => "PlaceOrder",
        Action::CancelOrder(_) => "CancelOrder",
        Action::SetAccountRole(_) => "SetAccountRole",
        Action::Liquidate(_) => "Liquidate",
        Action::CreateMarket(_) => "CreateMarket",
        Action::ActivateMarket(_) => "ActivateMarket",
        Action::HaltMarket(_) => "HaltMarket",
        Action::ResumeMarket(_) => "ResumeMarket",
        Action::RequestDelist(_) => "RequestDelist",
        Action::CompleteDelist(_) => "CompleteDelist",
        Action::SetFeeRecipient(_) => "SetFeeRecipient",
        Action::AmendMarketConfig(_) => "AmendMarketConfig",
        Action::SetEmergencyHalt(_) => "SetEmergencyHalt",
        Action::RecordDeposit(_) => "RecordDeposit",
        Action::CreditDeposit(_) => "CreditDeposit",
        Action::WithdrawRequest(_) => "WithdrawRequest",
        Action::WithdrawSettle(_) => "WithdrawSettle",
        Action::WithdrawRefund(_) => "WithdrawRefund",
        Action::SetSettlementPaused(_) => "SetSettlementPaused",
        Action::SetUserFeeRate(_) => "SetUserFeeRate",
        Action::SetReferrer(_) => "SetReferrer",
        Action::RegisterReferrer(_) => "RegisterReferrer",
        Action::SetGlobalRebateRatio(_) => "SetGlobalRebateRatio",
        Action::SetAccountRebateRatio(_) => "SetAccountRebateRatio",
        Action::SetInviterKeepRatio(_) => "SetInviterKeepRatio",
        Action::PlaceTriggerOrder(_) => "PlaceTriggerOrder",
        Action::CancelTriggerOrder(_) => "CancelTriggerOrder",
        Action::AmendTriggerOrder(_) => "AmendTriggerOrder",
        Action::PlaceOco(_) => "PlaceOco",
        Action::CancelOco(_) => "CancelOco",
        Action::SubmitOracleQuote(_) => "SubmitOracleQuote",
        Action::AmendOrder(_) => "AmendOrder",
        Action::MassCancel(_) => "MassCancel",
        Action::ClosePosition(_) => "ClosePosition",
        Action::SetLeverage(_) => "SetLeverage",
        Action::SetMarginMode(_) => "SetMarginMode",
        Action::SetIsolatedMargin(_) => "SetIsolatedMargin",
        Action::RegisterAgent(_) => "RegisterAgent",
        Action::RevokeAgent(_) => "RevokeAgent",
        Action::ScheduleCancel(_) => "ScheduleCancel",
        Action::BatchPlaceOrder(_) => "BatchPlaceOrder",
        Action::BatchModify(_) => "BatchModify",
        Action::BatchAmendTrigger(_) => "BatchAmendTrigger",
        Action::BatchSubmitOracleQuote(_) => "BatchSubmitOracleQuote",
    }
}
